/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author i3
 */
public class viewUrna extends javax.swing.JFrame {

        int imagem1 = 0;
        int imagem2 = 0;
        int Radio1 = 0;
        int Radio2 = 0;
        int Radio3 = 0;
        int Radio4 = 0;
        int Radio5 = 0;
        int Radio6 = 0;
        int Radio7 = 0;
        int Radio8 = 0;
        int Radio9 = 0;
        
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
    }
    /**
     * Creates new form viewUrna
     */
    public viewUrna() {
        initComponents();
        setIcon();
        setExtendedState(MAXIMIZED_BOTH);
        
        btnzerar.setVisible(false);
        lblresultado.setVisible(false);
        lblres2.setVisible(false);
        lblres1.setVisible(false);
        lblresultadoradio.setVisible(false);
        lblradres1.setVisible(false);
        lblradres2.setVisible(false);
        lblradres3.setVisible(false);
        lblradres4.setVisible(false);
        lblradres5.setVisible(false);
        lblradres6.setVisible(false);
        lblradres7.setVisible(false);
        lblradres8.setVisible(false);
        lblradres9.setVisible(false);
     
    }

    public void desaparecer(){
        
        lblresultado.setVisible(false);
        lblresultadoradio.setVisible(false);
        lblres2.setVisible(false);
        lblres1.setVisible(false);
        lblradres1.setVisible(false);
        lblradres2.setVisible(false);
        lblradres3.setVisible(false);
        lblradres4.setVisible(false);
        lblradres5.setVisible(false);
        lblradres6.setVisible(false);
        lblradres7.setVisible(false);
        lblradres8.setVisible(false);
        lblradres9.setVisible(false);   
    }
    
    public void aparecer(){
        
        lblresultado.setVisible(true);
        lblresultadoradio.setVisible(true);
        lblres2.setVisible(true);
        lblres1.setVisible(true);
        lblradres1.setVisible(true);
        lblradres2.setVisible(true);
        lblradres3.setVisible(true);
        lblradres4.setVisible(true);
        lblradres5.setVisible(true);
        lblradres6.setVisible(true);
        lblradres7.setVisible(true);
        lblradres8.setVisible(true);
        lblradres9.setVisible(true);
    }
    
    public void CorPreta(){
        
        lblresultado.setForeground(Color.BLACK);
        lblresultadoradio.setForeground(Color.BLACK);
        
        jLabel4.setForeground(Color.BLACK);
        jLabel3.setForeground(Color.BLACK);
        
        lblres1.setForeground(Color.BLACK);
        lblres2.setForeground(Color.BLACK);
    
        lblradres1.setForeground(Color.BLACK);
        lblradres2.setForeground(Color.BLACK);
        lblradres3.setForeground(Color.BLACK);
        lblradres4.setForeground(Color.BLACK);
        lblradres5.setForeground(Color.BLACK);
        lblradres6.setForeground(Color.BLACK);
        lblradres7.setForeground(Color.BLACK);
        lblradres8.setForeground(Color.BLACK);
        lblradres9.setForeground(Color.BLACK);
        
        jLabel6.setForeground(Color.BLACK);
        jLabel7.setForeground(Color.BLACK);
        jLabel8.setForeground(Color.BLACK);
        jLabel12.setForeground(Color.BLACK);
        jLabel13.setForeground(Color.BLACK);
        jLabel15.setForeground(Color.BLACK);
        jLabel17.setForeground(Color.BLACK);
        jLabel21.setForeground(Color.BLACK);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnrad1 = new javax.swing.JButton();
        btnrad2 = new javax.swing.JButton();
        btnrad3 = new javax.swing.JButton();
        btnrad4 = new javax.swing.JButton();
        btnrad5 = new javax.swing.JButton();
        btnrd6 = new javax.swing.JButton();
        btnrad7 = new javax.swing.JButton();
        btnrad8 = new javax.swing.JButton();
        btnrad9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        lblresultado = new javax.swing.JLabel();
        btnzerar = new javax.swing.JButton();
        lblres2 = new javax.swing.JLabel();
        lblres1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblresultadoradio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblradres1 = new javax.swing.JLabel();
        lblradres2 = new javax.swing.JLabel();
        lblradres3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblradres4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblradres5 = new javax.swing.JLabel();
        lblradres6 = new javax.swing.JLabel();
        lblradres7 = new javax.swing.JLabel();
        lblradres8 = new javax.swing.JLabel();
        lblradres9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Urna");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        btnVoltar.setBackground(new java.awt.Color(0, 0, 204));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 51));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DARIOGAY.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" SEJA BEM-VINDO A CENTRAL DE VOTAÇÕES DA DIVISÃO DE TECNOLOGIA EDUCACIONAL DE OLINDA.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(38, 38, 38))
        );

        jButton5.setBackground(new java.awt.Color(0, 0, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 51));
        jButton5.setText("Logo 1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 51));
        jButton6.setText("Logo 2");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnrad1.setBackground(new java.awt.Color(0, 0, 204));
        btnrad1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnrad1.setForeground(new java.awt.Color(255, 255, 51));
        btnrad1.setText("Rádio 1");
        btnrad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrad1ActionPerformed(evt);
            }
        });

        btnrad2.setBackground(new java.awt.Color(0, 0, 204));
        btnrad2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnrad2.setForeground(new java.awt.Color(255, 255, 51));
        btnrad2.setText("Rádio 2");
        btnrad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrad2ActionPerformed(evt);
            }
        });

        btnrad3.setBackground(new java.awt.Color(0, 0, 204));
        btnrad3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnrad3.setForeground(new java.awt.Color(255, 255, 51));
        btnrad3.setText("Radio 3");
        btnrad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrad3ActionPerformed(evt);
            }
        });

        btnrad4.setBackground(new java.awt.Color(0, 0, 204));
        btnrad4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnrad4.setForeground(new java.awt.Color(255, 255, 51));
        btnrad4.setText("Rádio 4");
        btnrad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrad4ActionPerformed(evt);
            }
        });

        btnrad5.setBackground(new java.awt.Color(0, 0, 204));
        btnrad5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnrad5.setForeground(new java.awt.Color(255, 255, 51));
        btnrad5.setText("Rádio 5");
        btnrad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrad5ActionPerformed(evt);
            }
        });

        btnrd6.setBackground(new java.awt.Color(0, 0, 204));
        btnrd6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnrd6.setForeground(new java.awt.Color(255, 255, 51));
        btnrd6.setText("Rádio 6");
        btnrd6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrd6ActionPerformed(evt);
            }
        });

        btnrad7.setBackground(new java.awt.Color(0, 0, 204));
        btnrad7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnrad7.setForeground(new java.awt.Color(255, 255, 51));
        btnrad7.setText("Radio 7");
        btnrad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrad7ActionPerformed(evt);
            }
        });

        btnrad8.setBackground(new java.awt.Color(0, 0, 204));
        btnrad8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnrad8.setForeground(new java.awt.Color(255, 255, 51));
        btnrad8.setText("Rádio 8");
        btnrad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrad8ActionPerformed(evt);
            }
        });

        btnrad9.setBackground(new java.awt.Color(0, 0, 204));
        btnrad9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnrad9.setForeground(new java.awt.Color(255, 255, 51));
        btnrad9.setText("Rádio 9");
        btnrad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrad9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnrad1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnrad2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnrad3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnrad4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnrad5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnrd6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnrad7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnrad8)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnrad9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(18, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrad1)
                    .addComponent(btnrad2)
                    .addComponent(btnrad3)
                    .addComponent(btnrad4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrad5)
                    .addComponent(btnrd6)
                    .addComponent(btnrad7)
                    .addComponent(btnrad8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnrad9)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jButton7.setBackground(new java.awt.Color(0, 0, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 51));
        jButton7.setText("Resultado");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        lblresultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblresultado.setForeground(new java.awt.Color(51, 204, 0));
        lblresultado.setText("Resultado da Imagem");

        btnzerar.setBackground(new java.awt.Color(0, 0, 204));
        btnzerar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnzerar.setForeground(new java.awt.Color(255, 255, 51));
        btnzerar.setText("Zerar Votação");
        btnzerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnzerarActionPerformed(evt);
            }
        });

        lblres2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblres2.setText("0");

        lblres1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblres1.setText("0");

        jLabel3.setText("Imagem 2");

        jLabel4.setText("Imagem 1");

        jLabel5.setText("x");

        lblresultadoradio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblresultadoradio.setForeground(new java.awt.Color(0, 153, 0));
        lblresultadoradio.setText("Resultado da Rádio");

        jLabel6.setText("Radio 1");

        jLabel7.setText("Radio 2");

        jLabel8.setText("Radio 3");

        jLabel9.setText("x");

        jLabel10.setText("x");

        lblradres1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblradres1.setText("0");

        lblradres2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblradres2.setText("0");

        lblradres3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblradres3.setText("0");

        jLabel11.setText("x");

        jLabel12.setText("Rádio 4");

        lblradres4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblradres4.setText("0");

        jLabel13.setText("Rádio 5");

        jLabel14.setText("x");

        jLabel15.setText("Rádio 6");

        jLabel16.setText("x");

        jLabel17.setText("Rádio 7");

        jLabel18.setText("x");

        jLabel19.setText("Rádio 8");

        jLabel20.setText("x");

        jLabel21.setText("Rádio 9");

        jLabel22.setText("x");

        lblradres5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblradres5.setText("0");

        lblradres6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblradres6.setText("0");

        lblradres7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblradres7.setText("0");

        lblradres8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblradres8.setText("0");

        lblradres9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblradres9.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(lblradres1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblradres2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addComponent(lblradres3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14))
                                    .addComponent(lblradres4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16))
                                    .addComponent(lblradres5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18))
                                    .addComponent(lblradres6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20))
                                    .addComponent(lblradres7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22))
                                    .addComponent(lblradres8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblradres9)
                                    .addComponent(jLabel21)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(lblresultadoradio)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(lblres1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblres2)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblresultado)
                                .addGap(39, 39, 39))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(468, 468, 468)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(btnzerar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)
                        .addComponent(jLabel12)
                        .addComponent(jLabel11)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)
                        .addComponent(jLabel22)
                        .addComponent(jLabel21)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblradres8)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblres2)
                                .addComponent(lblres1)
                                .addComponent(lblradres1)
                                .addComponent(lblradres2)
                                .addComponent(lblradres3)
                                .addComponent(lblradres4)
                                .addComponent(lblradres9))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblradres6)
                            .addComponent(lblradres5)
                            .addComponent(lblradres7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblresultadoradio)
                    .addComponent(lblresultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(btnzerar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        new viewPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
            imagem1++;
            lblres1.setText(Integer.toString(imagem1));
            
            CorPreta();
            desaparecer();
        
        
       JOptionPane.showMessageDialog(null,"Votado com Sucesso!");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        imagem2++;
        lblres2.setText(Integer.toString(imagem2));
        
        CorPreta();
        desaparecer();
        
        JOptionPane.showMessageDialog(null,"Votado com Sucesso!");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        aparecer();
       
        if(imagem1>imagem2){
            lblresultado.setText("Imagem 1 ganhou");
            jLabel4.setForeground(Color.GREEN);
            lblres1.setForeground(Color.GREEN);
            lblresultado.setForeground(Color.GREEN);
        }
        else if(imagem2>imagem1){
            lblresultado.setText("Imagem 2 ganhou");
            jLabel3.setForeground(Color.GREEN);
            lblres2.setForeground(Color.GREEN);
            lblresultado.setForeground(Color.GREEN);
        }
        else{
            lblresultado.setText("Empate");
            lblresultado.setForeground(Color.YELLOW);
            lblres1.setForeground(Color.RED);
            lblres2.setForeground(Color.RED);
        }
        
       
        if(Radio1>Radio2 && Radio1>Radio3 && Radio1>Radio4 && Radio1>Radio5 && Radio1>Radio6 && Radio1>Radio7 && Radio1>Radio8 && Radio1>Radio9){
            lblresultadoradio.setText("Rádio 1 ganhou");
            jLabel6.setForeground(Color.GREEN);
            lblradres1.setForeground(Color.GREEN);
            lblresultadoradio.setForeground(Color.GREEN);
        }
        else if(Radio2>Radio1 && Radio2>Radio3 && Radio2>Radio4 && Radio2>Radio5 && Radio2>Radio6 && Radio2>Radio7 && Radio2>Radio8 && Radio2>Radio9){
            lblresultadoradio.setText("Rádio 2 ganhou");
            jLabel7.setForeground(Color.GREEN);
            lblradres2.setForeground(Color.GREEN);
            lblresultadoradio.setForeground(Color.GREEN);
        }
        else if(Radio3>Radio1 && Radio3>Radio2 && Radio3>Radio4 && Radio3>Radio5 && Radio3>Radio6 && Radio3>Radio7 && Radio3>Radio8 && Radio3>Radio9){
            lblresultadoradio.setText("Rádio 3 ganhou");
            jLabel8.setForeground(Color.GREEN);
            lblradres3.setForeground(Color.GREEN);
            lblresultadoradio.setForeground(Color.GREEN);
        }
        else if(Radio4>Radio1 && Radio4>Radio2 && Radio4>Radio3 && Radio4>Radio5 && Radio4>Radio6 && Radio4>Radio7 && Radio4>Radio8 && Radio4>Radio9){
            lblresultadoradio.setText("Rádio 4 ganhou");
            jLabel12.setForeground(Color.GREEN);
            lblradres4.setForeground(Color.GREEN);
            lblresultadoradio.setForeground(Color.GREEN);
        }
        else if(Radio5>Radio1 && Radio5>Radio2 && Radio5>Radio3 && Radio5>Radio4 && Radio5>Radio6 && Radio5>Radio7 && Radio5>Radio8 && Radio5>Radio9){
            lblresultadoradio.setText("Rádio 5 ganhou");
            jLabel13.setForeground(Color.GREEN);
            lblradres5.setForeground(Color.GREEN);
            lblresultadoradio.setForeground(Color.GREEN);
        }
        else if(Radio6>Radio1 && Radio6>Radio2 && Radio6>Radio3 && Radio6>Radio4 && Radio6>Radio5 && Radio6>Radio7 && Radio6>Radio8 && Radio6>Radio9){
            lblresultadoradio.setText("Rádio 6 ganhou");
            jLabel15.setForeground(Color.GREEN);
            lblradres6.setForeground(Color.GREEN);
            lblresultadoradio.setForeground(Color.GREEN);
        }
        else if(Radio7>Radio1 && Radio7>Radio2 && Radio7>Radio3 && Radio7>Radio4 && Radio7>Radio5 && Radio7>Radio6 && Radio7>Radio8 && Radio7>Radio9){
            lblresultadoradio.setText("Rádio 7 ganhou");
            jLabel17.setForeground(Color.GREEN);
            lblradres7.setForeground(Color.GREEN);
            lblresultadoradio.setForeground(Color.GREEN);
        }
        else if(Radio8>Radio1 && Radio8>Radio2 && Radio8>Radio3 && Radio8>Radio4 && Radio8>Radio5 && Radio8>Radio6 && Radio8>Radio7 && Radio8>Radio9){
            lblresultadoradio.setText("Rádio 8 ganhou");
            jLabel19.setForeground(Color.GREEN);
            lblradres8.setForeground(Color.GREEN);
            lblresultadoradio.setForeground(Color.GREEN);
        }
        else if(Radio9>Radio1 && Radio9>Radio2 && Radio9>Radio3 && Radio9>Radio4 && Radio9>Radio5 && Radio9>Radio6 && Radio9>Radio7 && Radio9>Radio8){
            lblresultadoradio.setText("Rádio 9 ganhou");
            jLabel21.setForeground(Color.GREEN);
            lblradres9.setForeground(Color.GREEN);
            lblresultadoradio.setForeground(Color.GREEN);
        }
        else{
            lblresultadoradio.setText("Empate");
            lblresultadoradio.setForeground(Color.YELLOW);
        }
        
        btnzerar.setVisible(true);
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnzerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzerarActionPerformed
        // TODO add your handling code here:
        
        imagem1 = 0;
        imagem2 = 0;
        Radio1 = 0;
        Radio2 = 0;
        Radio3 = 0;
        Radio4 = 0;
        Radio5 = 0;
        Radio6 = 0;
        Radio7 = 0;
        Radio8 = 0;
        Radio9 = 0;
                
        desaparecer();
        
        lblres2.setText(Integer.toString(imagem1));
        lblres1.setText(Integer.toString(imagem2));
        lblradres1.setText(Integer.toString(Radio1));
        lblradres2.setText(Integer.toString(Radio2));
        lblradres3.setText(Integer.toString(Radio3));
        lblradres4.setText(Integer.toString(Radio4));
        lblradres5.setText(Integer.toString(Radio5));
        lblradres6.setText(Integer.toString(Radio6));
        lblradres7.setText(Integer.toString(Radio7));
        lblradres8.setText(Integer.toString(Radio8));
        lblradres9.setText(Integer.toString(Radio9));
        
        CorPreta();
        
    }//GEN-LAST:event_btnzerarActionPerformed

    private void btnrad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrad1ActionPerformed
        // TODO add your handling code here:
        
        Radio1++;
        lblradres1.setText(Integer.toString(Radio1));
        
        CorPreta();        
        desaparecer();
        
        JOptionPane.showMessageDialog(null,"Votado na Radio 1 com Sucesso!");
    }//GEN-LAST:event_btnrad1ActionPerformed

    private void btnrad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrad2ActionPerformed
        // TODO add your handling code here:
        
        Radio2++;
        lblradres2.setText(Integer.toString(Radio2));
       
        CorPreta();
        desaparecer();
        
        JOptionPane.showMessageDialog(null,"Votado na Radio 2 com Sucesso!");
    }//GEN-LAST:event_btnrad2ActionPerformed

    private void btnrad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrad3ActionPerformed
        // TODO add your handling code here:
        
        Radio3++;
        lblradres3.setText(Integer.toString(Radio3));
        
        CorPreta();
        desaparecer();
        
        JOptionPane.showMessageDialog(null,"Votado na Radio 3 com Sucesso!");
    }//GEN-LAST:event_btnrad3ActionPerformed

    private void btnrad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrad4ActionPerformed
        // TODO add your handling code here:
        Radio4++;
        lblradres4.setText(Integer.toString(Radio4));
        
        CorPreta();
        desaparecer();
        
         JOptionPane.showMessageDialog(null,"Votado na Radio 4 com Sucesso!");
    }//GEN-LAST:event_btnrad4ActionPerformed

    private void btnrad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrad5ActionPerformed
        // TODO add your handling code here:
        Radio5++;
        lblradres5.setText(Integer.toString(Radio5));
        
        CorPreta();     
        desaparecer();
        
        JOptionPane.showMessageDialog(null,"Votado na Radio 5 com Sucesso!");
    }//GEN-LAST:event_btnrad5ActionPerformed

    private void btnrd6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrd6ActionPerformed
        // TODO add your handling code here:
        Radio6++;
        lblradres6.setText(Integer.toString(Radio6)); 
        
        CorPreta();
        desaparecer();
        
        JOptionPane.showMessageDialog(null,"Votado na Radio 6 com Sucesso!");
    }//GEN-LAST:event_btnrd6ActionPerformed

    private void btnrad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrad7ActionPerformed
        // TODO add your handling code here:
        Radio7++; 
        lblradres7.setText(Integer.toString(Radio7));
        
        CorPreta();
        desaparecer();
        
        JOptionPane.showMessageDialog(null,"Votado na Radio 7 com Sucesso!");
    }//GEN-LAST:event_btnrad7ActionPerformed

    private void btnrad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrad8ActionPerformed
        // TODO add your handling code here:
        Radio8++;
        lblradres8.setText(Integer.toString(Radio8));
       
        CorPreta();
        desaparecer();
        
        JOptionPane.showMessageDialog(null,"Votado na Radio 8 com Sucesso!");
    }//GEN-LAST:event_btnrad8ActionPerformed

    private void btnrad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrad9ActionPerformed
        // TODO add your handling code here:
        Radio9++;
        lblradres9.setText(Integer.toString(Radio9));
        
        CorPreta();
        desaparecer();
        
        JOptionPane.showMessageDialog(null,"Votado na Radio 9 com Sucesso!");
    }//GEN-LAST:event_btnrad9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewUrna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btnrad1;
    private javax.swing.JButton btnrad2;
    private javax.swing.JButton btnrad3;
    private javax.swing.JButton btnrad4;
    private javax.swing.JButton btnrad5;
    private javax.swing.JButton btnrad7;
    private javax.swing.JButton btnrad8;
    private javax.swing.JButton btnrad9;
    private javax.swing.JButton btnrd6;
    private javax.swing.JButton btnzerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblradres1;
    private javax.swing.JLabel lblradres2;
    private javax.swing.JLabel lblradres3;
    private javax.swing.JLabel lblradres4;
    private javax.swing.JLabel lblradres5;
    private javax.swing.JLabel lblradres6;
    private javax.swing.JLabel lblradres7;
    private javax.swing.JLabel lblradres8;
    private javax.swing.JLabel lblradres9;
    private javax.swing.JLabel lblres1;
    private javax.swing.JLabel lblres2;
    private javax.swing.JLabel lblresultado;
    private javax.swing.JLabel lblresultadoradio;
    // End of variables declaration//GEN-END:variables

}
